# Feature Merging & Final Dataset

Welcome to the Python phase of my project! Most data releated stuff are already taken care by my SQL queries. Now i have three clean, aggregated CSV files in our `data/sql_outputs/` folder.

### Loading the Data

In [2]:
import pandas as pd
import os

data_dir = '../data/sql_outputs/'

orders_df = pd.read_csv(os.path.join(data_dir, 'order_features_with_returns.csv'))
customers_df = pd.read_csv(os.path.join(data_dir, 'customer_features.csv'))
products_df = pd.read_csv(os.path.join(data_dir, 'product_features.csv'))

print(f" Oders Shape: {orders_df.shape}")
print(f" Customers Shape: {customers_df.shape}")
print(f" Products Shape: {products_df.shape}")

 Oders Shape: (96999, 19)
 Customers Shape: (95420, 23)
 Products Shape: (32951, 17)

In [3]:
orders_df.head()

,order_id,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,num_items,total_price,avg_item_price,total_freight,freight_ratio,product_category,review_score,has_review_comment,actual_delivery_days,estimated_delivery_days,delivery_delay_days,is_late_delivery,return_probability_score,is_returned
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,sao paulo,SP,1,29.99,29.99,8.72,0.2908,utilidades_domesticas,4,1,8.4,15.5,-7.1,0,0.08,0
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,barreiras,BA,1,118.70,118.70,22.76,0.1917,perfumaria,4,1,13.8,19.1,-5.4,0,0.08,1
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,vianopolis,GO,1,159.90,159.90,19.22,0.1202,automotivo,5,0,9.4,26.6,-17.2,0,0.05,0
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,sao goncalo do amarante,RN,1,45.00,45.00,27.20,0.6044,pet_shop,5,1,13.2,26.2,-13.0,0,0.03,0
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,2018-02-13 21:18:39,santo andre,SP,1,19.90,19.90,8.72,0.4382,papelaria,5,0,2.9,12.1,-9.2,0,0.04,0

In [4]:
customers_df.head()

,customer_unique_id,total_orders,total_items_purchased,avg_items_per_order,total_spent,avg_order_value,total_freight,freight_to_value_ratio,total_reviews,avg_review_score,...,avg_delivery_days,late_deliveries,late_delivery_percentage,last_order_date,first_order_date,days_since_last_order,customer_lifetime_days,is_one_time_buyer,is_unhappy_customer,frequent_late_deliveries
0,0a0a92112bd4c708ca5fde585afaa872,1,8,8.0,13440.0,1680.0,224.08,0.0167,1,1.0,...,18.12,0,0.0,2017-09-29 15:24:52,2017-09-29 15:24:52,366.0,0.0,1,1,0
1,da122df9eeddfedc1dc1f5349a1a690c,2,2,1.0,7388.0,3694.0,183.63,0.0249,2,5.0,...,15.87,0,0.0,2017-04-01 15:58:41,2017-04-01 15:58:40,547.0,0.0,0,0,0
2,763c8b1c9c68a0229c42c9fc6f662b93,1,4,4.0,7160.0,1790.0,114.88,0.0160,1,1.0,...,11.30,0,0.0,2018-07-15 14:49:44,2018-07-15 14:49:44,77.0,0.0,1,1,0
3,dc4802a71eae9be1dd28f5d788ceb526,1,1,1.0,6735.0,6735.0,194.31,0.0289,1,5.0,...,18.74,0,0.0,2017-02-12 20:37:36,2017-02-12 20:37:36,595.0,0.0,1,0,0
4,459bef486812aa25204be022145caa62,1,1,1.0,6729.0,6729.0,193.21,0.0287,0,0.0,...,20.87,1,100.0,2018-07-25 18:10:17,2018-07-25 18:10:17,67.0,0.0,1,1,1

In [5]:
products_df.head()

,product_id,product_category_name,times_ordered,total_revenue,avg_price,avg_freight,total_reviews,avg_review_score,low_rating_count,five_star_count,low_rating_percentage,products_in_category,category_total_sales,category_avg_rating,price_segment,high_complaint_product,high_dissatisfaction_rate
0,bb50f2e236e5eea0100680137654686c,beleza_saude,187,63885.00,327.62,19.08,196,4.22,19,114,9.69,2444.0,2444.0,4.18,high,0,0
1,6cdd53843498f92890544667809f1595,beleza_saude,151,54730.20,350.83,27.97,155,4.32,17,103,10.97,2444.0,2444.0,4.18,high,0,0
2,d6160fb7873f184099d9bc95e30376af,pcs,35,48899.34,1397.12,40.77,35,4.57,3,28,8.57,30.0,30.0,4.15,high,0,0
3,d1c427060a0f73f6b889a5c7c61f2ac4,informatica_acessorios,323,47214.51,137.65,40.12,340,4.19,41,207,12.06,1639.0,1639.0,3.94,medium,0,0
4,99a4788cb24856965c36a24e339b6058,cama_mesa_banho,467,43025.56,88.17,16.49,482,3.90,80,238,16.60,3029.0,3029.0,3.86,medium,0,0

customers_df is perfectly aligned with our orders because every order has exactly one customer_unique_id. We can easily join these.

Instead of trying to join specific product IDs, we can aggregate our products_df to find the average risk/price metrics for each Product Category! Then, we join those category-level product features onto our orders based on the product_category.

### Merge Customer & Category Features

In [ ]:
df_merged = pd.merge(
    orders_df, 
    customers_df, 
    on='customer_unique_id', 
    how='left',
    suffixes=('', '_cust')
)

# Product Features (Aggregate by Category first)
category_risk_df = products_df.groupby('product_category_name').agg({
    'high_complaint_product': 'mean',
    'high_dissatisfaction_rate': 'mean',
    'avg_review_score': 'mean',
    'low_rating_percentage': 'mean'
}).reset_index()

# Rename columns so we know they are category-level averages
category_risk_df = category_risk_df.rename(columns={
    'high_complaint_product': 'category_complaint_rate',
    'high_dissatisfaction_rate': 'category_dissatisfaction_rate',
    'avg_review_score': 'category_avg_rating',
    'low_rating_percentage': 'category_low_rating_pct'
})

# Merge Category Features
df_final = pd.merge(
    df_merged,
    category_risk_df,
    left_on='product_category',
    right_on='product_category_name',
    how='left'
)

# Drop the redundant join key
if 'product_category_name' in df_final.columns:
    df_final = df_final.drop('product_category_name', axis=1)

print(f" Final Merged Shape: {df_final.shape}")
df_final.head()

 Final Merged Shape: (96999, 45)

,order_id,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,num_items,total_price,avg_item_price,total_freight,freight_ratio,...,first_order_date,days_since_last_order,customer_lifetime_days,is_one_time_buyer,is_unhappy_customer,frequent_late_deliveries,category_complaint_rate,category_dissatisfaction_rate,category_avg_rating,category_low_rating_pct
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,sao paulo,SP,1,29.99,29.99,8.72,0.2908,...,2017-09-04 11:26:38,364.0,28.0,0,0,0,0.167452,0.173876,4.059670,15.203362
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,barreiras,BA,1,118.70,118.70,22.76,0.1917,...,2018-07-24 20:41:37,68.0,0.0,1,0,0,0.154378,0.193548,4.112074,15.886233
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,vianopolis,GO,1,159.90,159.90,19.22,0.1202,...,2018-08-08 08:38:49,54.0,0.0,1,0,0,0.180526,0.184737,4.023300,15.936200
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,sao goncalo do amarante,RN,1,45.00,45.00,27.20,0.6044,...,2017-11-18 19:28:06,316.0,0.0,1,0,0,0.134910,0.155772,4.145104,13.556912
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,2018-02-13 21:18:39,santo andre,SP,1,19.90,19.90,8.72,0.4382,...,2018-02-13 21:18:39,229.0,0.0,1,0,0,0.130742,0.159011,4.201955,13.265135

Even though we used COALESCE heavily in our SQL scripts to prevent NULLs, our df_final will still have a few missing values.

610 products that didn't have a category in SQL, i labeled them as 'unknown'

For missing continuous features (like category risk), the best practice is to impute them with the median value so we don't skew the distribution.

### Fill the Missing values

In [ ]:
missing_counts = df_final.isnull().sum()
print("Columns with missing values before imputation:")
print(missing_counts[missing_counts > 0])
print("-" * 40)
# change  missing category risk metrics with the global median
cols_to_fill_median = [
    'category_complaint_rate', 
    'category_dissatisfaction_rate', 
    'category_avg_rating', 
    'category_low_rating_pct'
]
for col in cols_to_fill_median:
    if col in df_final.columns:
        # I am using median() because mean() is sensitive to outliers
        df_final[col] = df_final[col].fillna(df_final[col].median())
# Fill any remaining edge-case NULLs with 0
df_final = df_final.fillna(0)

# Verify our data is perfectly clean now 
print(f"Total missing values remaining: {df_final.isnull().sum().sum()}")

Columns with missing values before imputation:
category_complaint_rate          1340
category_dissatisfaction_rate    1340
category_avg_rating              1340
category_low_rating_pct          1340
dtype: int64
----------------------------------------
Total missing values remaining: 0

In our orders_df, we have a column called return_probability_score. We used this continuous score purely to simulate our binary is_returned flag.

If we feed return_probability_score into an XGBoost or Random Forest model, the model will essentially "cheat". It will realize that this score directly correlates with the target variable and will ignore all our other features, resulting in 100% fake accuracy. We MUST drop it!

We also need to drop arbitrary identifiers (like order_id) because they have no predictive power.

### Feature Selection

In [10]:
import os

#  TEMPORAL FEATURE ENGINEERING
# Convert timestamp string to actual Pandas datetime object
df_final['order_purchase_timestamp'] = pd.to_datetime(df_final['order_purchase_timestamp'])

# Extract the Month and Day of Week as numbers so the ML model can read them
df_final['purchase_month'] = df_final['order_purchase_timestamp'].dt.month
df_final['purchase_day_of_week'] = df_final['order_purchase_timestamp'].dt.dayofweek

# 2. Drop ONLY the raw strings that the model can't read
cols_to_drop = [
    'order_id', 
    'customer_unique_id', 
    'order_purchase_timestamp', # We drop the raw string because we extracted Month/Day!
    'return_probability_score'  # DROP DATA LEAKAGE! We MUST drop this so the model doesn't cheat.
]

df_ml = df_final.drop(columns=[c for c in cols_to_drop if c in df_final.columns])

print("Target Variable (is_returned) Distribution:")
print(df_ml['is_returned'].value_counts(normalize=True) * 100)

#  Save the final dataset
os.makedirs('../data/final', exist_ok=True)
df_ml.to_csv('../data/final/ml_ready_dataset.csv', index=False)

print("\n SUCCESS! Saved ml_ready_dataset.csv to data/final/")
print(f"Final ML Shape: {df_ml.shape}")

Target Variable (is_returned) Distribution:
is_returned
0    81.957546
1    18.042454
Name: proportion, dtype: float64

 SUCCESS! Saved ml_ready_dataset.csv to data/final/
Final ML Shape: (96999, 43)